Repository NextPick/backend, pull requests merged in 2024-10, with the labels that each got.

#16 Feat/question category
  build.gradle
  src/main/java/com/nextPick/questionCategory/entity/QuestionCategory.java
  src/main/java/com/nextPick/questionCategory/repository/QuestionCategoryRepository.java
  src/main/java/com/nextPick/questionList/controller/QuestionListController.java
  src/main/java/com/nextPick/questionList/dto/QuestionListDto.java
  src/main/java/com/nextPick/questionList/entity/QuestionList.java
  src/main/java/com/nextPick/questionList/repository/QuestionListRepository.java
  src/main/java/com/nextPick/questionList/service/QuestionListService.java
Labels: enhancement

#17 feat:#5 security 적용 및 patch삭제 + 버그 수정
  src/main/java/com/nextPick/exception/ExceptionCode.java
  src/main/java/com/nextPick/member/controller/MemberController.java
  src/main/java/com/nextPick/member/dto/MemberDto.java
  src/main/java/com/nextPick/member/entity/Member.java
  src/main/java/com/nextPick/member/mapper/MemberMapper.java
  src/main/java/com/nextPick/member/service/MemberService.java
  src/main/java/com/nextPick/utils/ExtractMemberAndVerify.java
Labels: bug, enhancement

#18 feat:#5 member principal 간략화
  src/main/java/com/nextPick/member/controller/MemberController.java
  src/main/java/com/nextPick/member/service/MemberService.java
  src/main/java/com/nextPick/questionList/service/QuestionListService.java
  src/main/java/com/nextPick/utils/ExtractMemberAndVerify.java
Labels: enhancement

#27 QuestionList / QuestionCategory / Member / Keyword 기본 구현
  src/main/java/com/nextPick/keyword/entity/Keyword.java
  src/main/java/com/nextPick/keyword/repository/KeywordRepository.java
  src/main/java/com/nextPick/keyword/service/KeywordService.java
  src/main/java/com/nextPick/questionCategory/entity/QuestionCategory.java
  src/main/java/com/nextPick/questionList/entity/QuestionList.java
  src/main/java/com/nextPick/questionList/service/QuestionListService.java
  src/main/java/com/nextPick/questionList/service/userCostomDic.dic
Labels: bug, enhancement

#30 feat:#25 QuestionList 연관관계 설정
  src/main/java/com/nextPick/questionCategory/entity/QuestionCategory.java
  src/main/java/com/nextPick/questionList/controller/QuestionListController.java
  src/main/java/com/nextPick/questionList/entity/QuestionList.java
  src/main/java/com/nextPick/questionList/service/QuestionListService.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: enhancement

#32 feat:#31 SQL Data Insert
  src/main/java/com/nextPick/keyword/service/KeywordService.java
  src/main/java/com/nextPick/member/controller/MemberController.java
  src/main/java/com/nextPick/member/service/MemberService.java
  src/main/java/com/nextPick/questionCategory/entity/QuestionCategory.java
  src/main/java/com/nextPick/questionList/controller/utils/ExtractMemberAndVerify.java
  src/main/java/com/nextPick/questionList/controller/utils/UriCreator.java
  src/main/java/com/nextPick/questionList/entity/QuestionList.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: enhancement

#33 feat:#14 사용자 응답 형태소 분석, 맥락 파악, 단어간 관계도 설정
  src/main/java/com/nextPick/exception/ExceptionCode.java
  src/main/java/com/nextPick/keyword/entity/Keyword.java
  src/main/java/com/nextPick/keyword/service/KeywordService.java
  src/main/java/com/nextPick/member/controller/MemberController.java
  src/main/java/com/nextPick/member/service/MemberService.java
  src/main/java/com/nextPick/questionCategory/entity/QuestionCategory.java
  src/main/java/com/nextPick/questionList/controller/QuestionListController.java
  src/main/java/com/nextPick/questionList/entity/QuestionList.java
  src/main/java/com/nextPick/questionList/service/QuestionListService.java
  src/main/java/com/nextPick/questionList/service/userCostomDic.dic
  src/main/java/com/nextPick/utils/ExtractMemberAndVerify.java
  src/main/java/com/nextPick/utils/UriCreator.java
  src/main/resources/data.sql
  src/main/resources/userCustomDic.txt
Labels: enhancement

#35 Feat/morpheme #14 형태소 분석 심화 분석 및 정규화 작업 진행도 90%
  src/main/java/com/nextPick/questionList/service/QuestionListService.java
  src/main/resources/data.sql
  src/main/resources/userCustomDic.txt
Labels: bug, enhancement

#36 feat:#14 형태소 분석 심화 분석 및 정규화 작업 진행도 95%
  src/main/java/com/nextPick/questionList/service/QuestionListService.java
  src/main/resources/SynonymsDic.txt
Labels: enhancement

#40 feat:#14 openai chatGPT 연동
  src/main/java/com/nextPick/api/openai/config/OpenAiConfig.java
  src/main/java/com/nextPick/api/openai/controller/OpenAiController.java
  src/main/java/com/nextPick/api/openai/dto/ChatGPTRequest.java
  src/main/java/com/nextPick/api/openai/dto/ChatGPTResponse.java
  src/main/java/com/nextPick/api/openai/dto/Message.java
  src/main/java/com/nextPick/questionList/service/QuestionListService.java
  src/main/java/com/nextPick/synonyms/entity/Synonyms.java
  src/main/java/com/nextPick/synonyms/repository/SynonymsRepository.java
  src/main/resources/data.sql
  src/main/resources/userCustomDic.txt
Labels: enhancement

#44 feat:#14 openai chatGPT 프롬포트 작성
  src/main/java/com/nextPick/questionList/controller/QuestionListController.java
  src/main/java/com/nextPick/questionList/service/OldQuestionListService.java
  src/main/java/com/nextPick/questionList/service/QuestionListService.java
Labels: enhancement

#61 feat:#25 QuestionList CRUD 및 OpenAi 적용
  src/main/java/com/nextPick/exception/ExceptionCode.java
  src/main/java/com/nextPick/keyword/entity/Keyword.java
  src/main/java/com/nextPick/keyword/repository/KeywordRepository.java
  src/main/java/com/nextPick/keyword/service/KeywordService.java
  src/main/java/com/nextPick/questionList/config/OpenAiConfig.java
  src/main/java/com/nextPick/questionList/controller/QuestionListController.java
  src/main/java/com/nextPick/questionList/dto/QuestionListDto.java
  src/main/java/com/nextPick/questionList/entity/QuestionList.java
  src/main/java/com/nextPick/questionList/mapper/QuestionListMapper.java
  src/main/java/com/nextPick/questionList/repository/QuestionListRepository.java
  src/main/java/com/nextPick/questionList/service/OldQuestionListService.java
  src/main/java/com/nextPick/questionList/service/QuestionListService.java
  src/main/resources/data.sql
Labels: bug, enhancement

#78 feat:#77 Solves 구현
  src/main/java/com/nextPick/exception/ExceptionCode.java
  src/main/java/com/nextPick/keyword/entity/Keyword.java
  src/main/java/com/nextPick/keyword/repository/KeywordRepository.java
  src/main/java/com/nextPick/keyword/service/KeywordService.java
  src/main/java/com/nextPick/member/entity/Member.java
  src/main/java/com/nextPick/questionList/entity/QuestionList.java
  src/main/java/com/nextPick/questionList/service/OldQuestionListService.java
  src/main/java/com/nextPick/questionList/service/QuestionListService.java
  src/main/java/com/nextPick/solves/controller/SolvesController.java
  src/main/java/com/nextPick/solves/dto/SolvesDto.java
  src/main/java/com/nextPick/solves/entity/Solves.java
  src/main/java/com/nextPick/solves/mapper/SolvesMapper.java
  src/main/java/com/nextPick/solves/repository/SolvesRepository.java
  src/main/java/com/nextPick/solves/service/SolvesService.java
  src/main/java/com/nextPick/synonyms/entity/Synonyms.java
  src/main/java/com/nextPick/synonyms/repository/SynonymsRepository.java
  src/main/resources/SynonymsDic.txt
  src/main/resources/data.sql
  src/main/resources/userCustomDic.txt
Labels: enhancement

#81 feat:#25 QuestionList 디버깅
  src/main/java/com/nextPick/exception/ExceptionCode.java
  src/main/java/com/nextPick/member/controller/MemberController.java
  src/main/java/com/nextPick/member/dto/MemberDto.java
  src/main/java/com/nextPick/member/service/MemberService.java
  src/main/java/com/nextPick/questionList/controller/QuestionListController.java
  src/main/java/com/nextPick/questionList/dto/QuestionListDto.java
  src/main/java/com/nextPick/questionList/repository/QuestionListRepository.java
  src/main/java/com/nextPick/questionList/service/QuestionListService.java
  src/main/java/com/nextPick/solves/controller/SolvesController.java
  src/main/java/com/nextPick/solves/repository/SolvesRepository.java
  src/main/java/com/nextPick/solves/service/SolvesService.java
Labels: bug

#82 fix:#5 member 수정 제거, 중복 체크 누락 fix
  src/main/java/com/nextPick/member/controller/MemberController.java
  src/main/java/com/nextPick/member/service/MemberService.java
  src/main/resources/data.sql
Labels: bug

#89 feat:#88 Reports 구현
  src/main/java/com/nextPick/exception/ExceptionCode.java
  src/main/java/com/nextPick/member/controller/MemberController.java
  src/main/java/com/nextPick/member/dto/MemberDto.java
  src/main/java/com/nextPick/member/entity/Member.java
  src/main/java/com/nextPick/member/mapper/MemberMapper.java
  src/main/java/com/nextPick/member/service/MemberService.java
  src/main/java/com/nextPick/report/controller/ReportController.java
  src/main/java/com/nextPick/report/dto/ReportDto.java
  src/main/java/com/nextPick/report/entity/Report.java
  src/main/java/com/nextPick/report/repository/ReportRepository.java
  src/main/java/com/nextPick/report/service/ReportService.java
Labels: enhancement

#90 fix:#88 Reports mapper 누락 수정
  src/main/java/com/nextPick/report/mapper/ReportMapper.java
Labels: bug

#92 fix:#15 면접 피드백 & 멘토 피드백 버그 수정
  src/main/java/com/nextPick/feedbacks/interview/contorller/InterviewController.java
  src/main/java/com/nextPick/feedbacks/interview/dto/InterviewDto.java
  src/main/java/com/nextPick/feedbacks/interview/mapper/InterviewMapper.java
  src/main/java/com/nextPick/feedbacks/interview/repository/InterviewRepository.java
  src/main/java/com/nextPick/feedbacks/interview/service/InterviewService.java
  src/main/java/com/nextPick/feedbacks/mentor/controller/MentorController.java
  src/main/java/com/nextPick/feedbacks/mentor/dto/MentorDto.java
  src/main/java/com/nextPick/feedbacks/mentor/entity/Mentor.java
  src/main/java/com/nextPick/feedbacks/mentor/mapper/MentorMapper.java
  src/main/java/com/nextPick/feedbacks/mentor/repository/MentorRepository.java
  src/main/java/com/nextPick/feedbacks/mentor/service/MentorService.java
  src/main/java/com/nextPick/member/dto/MemberDto.java
  src/main/java/com/nextPick/member/entity/Member.java
Labels: bug

#93 fix:#5 Member 버그 수정
  src/main/java/com/nextPick/member/controller/MemberController.java
  src/main/java/com/nextPick/member/entity/Member.java
  src/main/java/com/nextPick/report/service/ReportService.java
Labels: bug

#94 fix:#5 member 버그 수정 및 type 추가 관련
  src/main/java/com/nextPick/member/controller/MemberController.java
  src/main/java/com/nextPick/member/dto/MemberDto.java
Labels: bug

#95 fix:#15 #5 #77 #88 전반적인 모든 오류 수정
  src/main/java/com/nextPick/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/nextPick/config/SecurityConfiguration.java
  src/main/java/com/nextPick/exception/ExceptionCode.java
  src/main/java/com/nextPick/exception/ForbiddenException.java
  src/main/java/com/nextPick/feedbacks/interview/contorller/InterviewController.java
  src/main/java/com/nextPick/feedbacks/mentor/controller/MentorController.java
  src/main/java/com/nextPick/member/controller/MemberController.java
  src/main/java/com/nextPick/member/dto/MemberDto.java
  src/main/java/com/nextPick/member/service/MemberService.java
  src/main/java/com/nextPick/nextPickApplication.java
  src/main/java/com/nextPick/questionList/entity/QuestionList.java
Labels: bug

#96 feat:#5 member 경력 추가
  src/main/java/com/nextPick/member/dto/MemberDto.java
  src/main/java/com/nextPick/member/entity/Member.java
Labels: enhancement

#122 feat:#120 Speech API 적용
  src/main/java/com/nextPick/speechAPI/SpeechController.java
  src/main/java/com/nextPick/speechAPI/SpeechService.java
  src/main/java/com/nextPick/speechAPI/Transcription.java
  src/main/java/com/nextPick/speechAPI/TranscriptionController.java
  src/main/java/com/nextPick/speechAPI/TranscriptionDTO.java
  src/main/java/com/nextPick/speechAPI/TranscriptionMapper.java
  src/main/java/com/nextPick/speechAPI/TranscriptionRepository.java
  src/main/java/com/nextPick/speechAPI/TranscriptionService.java
Labels: bug, enhancement

#124 Feat/statistics 통계 추가
  src/main/java/com/nextPick/eventListener/CustomEvent.java
  src/main/java/com/nextPick/eventListener/EventCaseEnum.java
  src/main/java/com/nextPick/eventListener/ServiceEventListener.java
  src/main/java/com/nextPick/exception/ExceptionCode.java
  src/main/java/com/nextPick/questionList/service/QuestionListService.java
  src/main/java/com/nextPick/speechAPI/ClovaSpeechClient.java
  src/main/java/com/nextPick/speechAPI/NaverCloud.java
  src/main/java/com/nextPick/speechAPI/NaverController.java
  src/main/java/com/nextPick/statistics/controller/StatisticsController.java
  src/main/java/com/nextPick/statistics/dto/StatisticsDto.java
  src/main/java/com/nextPick/statistics/entity/Statistics.java
  src/main/java/com/nextPick/statistics/mapper/StatisticsMapper.java
  src/main/java/com/nextPick/statistics/repository/StatisticsRepository.java
  src/main/java/com/nextPick/statistics/service/StatisticsService.java
Labels: enhancement

#127 Feat/statistics
  build.gradle
  src/main/java/com/nextPick/statistics/mapper/StatisticsMapper.java
  src/main/resources/data.sql
Labels: bug, enhancement

#128 feat:#5 member Response 추가
  src/main/java/com/nextPick/member/controller/MemberController.java
  src/main/java/com/nextPick/member/dto/MemberDto.java
  src/main/java/com/nextPick/member/mapper/MemberMapper.java
  src/main/java/com/nextPick/member/repository/MemberRepository.java
  src/main/java/com/nextPick/member/service/MemberService.java
Labels: bug, enhancement

#132 Feat/questioncategory feat:#11 QuestionCategory Read 추가
  src/main/java/com/nextPick/aws/controller/AwsController.java
  src/main/java/com/nextPick/questionCategory/controller/QuestionCategoryController.java
  src/main/java/com/nextPick/questionCategory/dto/QuestionCategoryDto.java
  src/main/java/com/nextPick/questionCategory/mapper/QuestionCategoryMapper.java
  src/main/java/com/nextPick/questionCategory/service/QuestionCategoryService.java
Labels: enhancement

#135 feat:#11 인터뷰 기능 추가
  src/main/java/com/nextPick/feedbacks/interview/contorller/InterviewController.java
  src/main/java/com/nextPick/feedbacks/interview/dto/InterviewDto.java
  src/main/java/com/nextPick/feedbacks/interview/mapper/InterviewMapper.java
  src/main/java/com/nextPick/feedbacks/interview/repository/InterviewRepository.java
  src/main/java/com/nextPick/feedbacks/interview/service/InterviewService.java
Labels: bug, enhancement

#141 feat: login Response Body contain nickname
  src/main/java/com/nextPick/auth/filter/JwtAuthenticationFilter.java
Labels: bug, enhancement

#143 feat:#25 api 추가
  src/main/java/com/nextPick/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/nextPick/questionList/controller/QuestionListController.java
  src/main/java/com/nextPick/questionList/dto/QuestionListDto.java
  src/main/java/com/nextPick/questionList/mapper/QuestionListMapper.java
  src/main/java/com/nextPick/questionList/service/QuestionListService.java
  src/main/java/com/nextPick/solves/controller/SolvesController.java
  src/main/java/com/nextPick/solves/dto/SolvesDto.java
  src/main/java/com/nextPick/solves/entity/Solves.java
  src/main/java/com/nextPick/solves/mapper/SolvesMapper.java
  src/main/java/com/nextPick/solves/repository/SolvesRepository.java
  src/main/java/com/nextPick/solves/service/SolvesService.java
  src/main/resources/data.sql
Labels: bug, enhancement

#145 .github/workflows 캐싱 적용
  .github/workflows/main.yml
Labels: enhancement

#147 docker remake jar file
  src/main/java/com/nextPick/speechAPI/SpeechToTextService.java
Labels: enhancement

#150 docker main.yml for make stt.json
  .github/workflows/main.yml
Labels: bug, enhancement

#154 main.yml 수정
  .github/workflows/main.yml
Labels: enhancement

#156 main.yml 수정
  .github/workflows/main.yml
Labels: bug, enhancement

#157 main.yml 과 application.yml 수정
  .github/workflows/main.yml
  src/main/resources/application.yml
Labels: bug, enhancement

#158 main.yml 수정
  .github/workflows/main.yml
Labels: bug

#160 feat:통계 기능 수정
  .gitignore
  src/main/java/com/nextPick/statistics/controller/StatisticsController.java
  src/main/java/com/nextPick/statistics/entity/Statistics.java
  src/main/java/com/nextPick/statistics/repository/StatisticsRepository.java
  src/main/java/com/nextPick/statistics/service/StatisticsService.java
  src/main/resources/data.sql
Labels: bug, enhancement

#162 Feat/admin page
  src/main/java/com/nextPick/feedbacks/interview/service/InterviewService.java
  src/main/java/com/nextPick/member/service/MemberService.java
  src/main/java/com/nextPick/statistics/controller/StatisticsController.java
  src/main/java/com/nextPick/statistics/entity/Statistics.java
  src/main/java/com/nextPick/statistics/service/StatisticsService.java
Labels: bug, enhancement

#167 Feat/admin page
  src/main/java/com/nextPick/config/SecurityConfiguration.java
  src/main/java/com/nextPick/questionList/dto/QuestionListDto.java
  src/main/java/com/nextPick/questionList/service/QuestionListService.java
Labels: bug, enhancement

#170 test
  src/main/java/com/nextPick/helper/email/EmailVerificationService.java
Labels: bug
